[machine]
  type = "sifive_u"
  kernel = "tools/qemu/egos.elf"
  firmware = "tools/qemu/bios.bin"

[smp-opts]
   cpus = "5"

# The actual number of CPU cores is (smp-opts.cpus - 1).
# In other words, smp-opts.cpus=5 means a 4-core CPU machine.
# The reason is that core #0 of sifive_u is an E31 core, which does not
# support the S-mode. We thus disabled this core within BIOS (bios.bin).

[memory]
  size = "256M"

[drive]
  if = "sd"
  format = "raw"
  file = "tools/disk.img"

# QEMU (v7.0.0 or higher) supports SD card emulation for the sifive_u machine type.
